version: '3'
services:
    api:
        build: .
        depends_on: 
            - postgres
        ports:
            - 8000:8000
        volumes:
            - ./:/usr/src/app:ro
        command: uvicron app.main:app --host 0.0.0.0 --port 8000 --reload
        environment:
            - DATABASE_HOSTNAME=postgres
            - DATABASE_PORT=5432
            - DATABASE_PASSWORD=123
            - DATABASE_USERNAME=postgres
            - DATABASE_NAME=fastapi
            - SECRET_KEY="09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
            - ALGORITHM="HS256"
            - ACCESS_TOKkEN_EXPIRE_MINUTES=30
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=123
            - POSTGRES_DB=fastapi

        volume: 
            - postgres_db:/var/lib/postgresql/data

volumes:
    postgres_db